#!/bin/bash

numberofjobs=49
pidarray=()
for i in `seq 0 $numberofjobs`;
        do
                if [ $i -lt 10 ]; then   wd=do0$i; else wd=do$i ;fi;
                if [ ! -d $wd ]; then echo creating $wd; mkdir $wd ; fi
                cp mw_on_pc.py $wd
		cp newpercfinder.py $wd
                
                cd $wd
                python3 -u mw_on_pc.py &>out.dat &
		pidarray+=($!)
                cd ..
                
                
        done

