#!/bin/bash

numberofjobs=99
pidarray=()
for i in `seq 0 $numberofjobs`;
        do
                if [ $i -lt 10 ]; then   wd=do0$i; else wd=do$i ;fi;
                if [ ! -d $wd ]; then echo creating $wd; mkdir $wd ; fi
                cp rw_food_multiple_walkers.py $wd
                
                cd $wd
                python3 -u rw_food_mult_suc.py 5 &>out.dat &
		pidarray+=($!)
                cd ..
                
                
        done
for pid in ${pidarray[@]}
do
	wait $pid
done

/home/stei_s2/./mergesamples 
